# =============================================================================
# Google Cloud Build Configuration
# =============================================================================
# This configuration file defines the CI/CD pipeline for the Thesis Validator
# service using Google Cloud Build.
#
# The pipeline includes:
# 1. Install dependencies
# 2. Run linting
# 3. Run type checking
# 4. Run tests
# 5. Build Docker image
# 6. Push to Artifact Registry
# 7. Deploy to Cloud Run (optional, based on branch)
#
# Required Substitutions:
# - _REGION: Google Cloud region (default: us-central1)
# - _REPOSITORY: Artifact Registry repository name
# - _SERVICE_NAME: Cloud Run service name
#
# Required IAM Permissions for Cloud Build Service Account:
# - roles/artifactregistry.writer
# - roles/run.admin
# - roles/iam.serviceAccountUser
# =============================================================================

substitutions:
  _REGION: us-central1
  _REPOSITORY: thesis-validator
  _SERVICE_NAME: thesis-validator
  _NODE_VERSION: '20'
  _PR_NUMBER: ''  # Set by GitHub trigger for PRs, empty for manual builds
  _TAG: latest  # Image tag, override with SHORT_SHA for triggered builds
  _SKIP_TESTS: 'true'  # Skip tests by default (requires Redis/PostgreSQL)

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ---------------------------------------------------------------------------
  # Step 1: Install Dependencies
  # ---------------------------------------------------------------------------
  - id: 'install-dependencies'
    name: 'node:${_NODE_VERSION}-alpine'
    dir: 'thesis-validator'
    entrypoint: 'npm'
    args: ['ci']

  # ---------------------------------------------------------------------------
  # Step 2: Run Linting
  # ---------------------------------------------------------------------------
  - id: 'lint'
    name: 'node:${_NODE_VERSION}-alpine'
    dir: 'thesis-validator'
    entrypoint: 'npm'
    args: ['run', 'lint']
    waitFor: ['install-dependencies']

  # ---------------------------------------------------------------------------
  # Step 3: Run Type Checking
  # ---------------------------------------------------------------------------
  - id: 'typecheck'
    name: 'node:${_NODE_VERSION}-alpine'
    dir: 'thesis-validator'
    entrypoint: 'npm'
    args: ['run', 'typecheck']
    waitFor: ['install-dependencies']

  # ---------------------------------------------------------------------------
  # Step 4: Run Tests (unit tests only, skipped if no test infrastructure)
  # ---------------------------------------------------------------------------
  # NOTE: Full integration tests require Redis/PostgreSQL. For CI without
  # test infrastructure, tests are skipped. Set _SKIP_TESTS=false to enable.
  - id: 'test'
    name: 'node:${_NODE_VERSION}-alpine'
    dir: 'thesis-validator'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "${_SKIP_TESTS}" = "true" ]; then
          echo "Skipping tests (_SKIP_TESTS=true)"
        else
          npm run test
        fi
    waitFor: ['install-dependencies']
    env:
      - 'NODE_ENV=test'
      - 'CI=true'

  # ---------------------------------------------------------------------------
  # Step 5: Build Docker Image
  # ---------------------------------------------------------------------------
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'thesis-validator'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Try to pull cache image (ignore failure for first build)
        docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest || true
        # Build with cache if available
        docker build \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG} \
          --cache-from ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest \
          .
    waitFor: ['lint', 'typecheck', 'test']

  # ---------------------------------------------------------------------------
  # Step 6: Push Docker Image to Artifact Registry
  # ---------------------------------------------------------------------------
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    waitFor: ['build-image']

  # ---------------------------------------------------------------------------
  # Step 7: Deploy to Cloud Run (Production)
  # Runs on main branch OR manual builds (when BRANCH_NAME is empty)
  # ---------------------------------------------------------------------------
  - id: 'deploy-production'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ -z "$BRANCH_NAME" ]; then
          gcloud run deploy ${_SERVICE_NAME} \
            --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG} \
            --region ${_REGION} \
            --platform managed \
            --port 3000 \
            --vpc-connector tv-vpc-connector \
            --set-env-vars "NODE_ENV=production,LLM_PROVIDER=vertex-ai,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_REGION=${_REGION},CORS_ORIGINS=*" \
            --set-secrets "JWT_SECRET=thesis-validator-jwt-secret:latest,OPENAI_API_KEY=openai-api-key:latest,TAVILY_API_KEY=tavily-api-key:latest" \
            --memory 2Gi \
            --cpu 2 \
            --min-instances 0 \
            --max-instances 10 \
            --timeout 300 \
            --concurrency 80
          echo "Deployed to production"
        else
          echo "Skipping production deployment (not on main branch)"
        fi
    waitFor: ['push-image']

  # ---------------------------------------------------------------------------
  # Step 8: Deploy to Cloud Run (Staging)
  # Runs on develop branch or PRs to main
  # ---------------------------------------------------------------------------
  - id: 'deploy-staging'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "develop" ] || [ -n "$_PR_NUMBER" ]; then
          gcloud run deploy ${_SERVICE_NAME}-staging \
            --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG} \
            --region ${_REGION} \
            --platform managed \
            --no-allow-unauthenticated \
            --set-env-vars "NODE_ENV=staging,LLM_PROVIDER=vertex-ai,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_REGION=${_REGION}" \
            --set-secrets "JWT_SECRET=thesis-validator-jwt-secret:latest,OPENAI_API_KEY=openai-api-key:latest,TAVILY_API_KEY=tavily-api-key:latest" \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 3 \
            --timeout 300 \
            --concurrency 40
          echo "Deployed to staging"
        else
          echo "Skipping staging deployment"
        fi
    waitFor: ['push-image']

# Images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'

# Build timeout (30 minutes)
timeout: '1800s'

# Trigger configuration (can also be set via Cloud Console or gcloud)
# trigger:
#   github:
#     owner: 'your-org'
#     name: 'nextgen-CDD'
#     push:
#       branch: '^(main|develop)$'
#     pullRequest:
#       branch: '^main$'
